Created a branch called remoted-branch
moise-mulungu/my-portfolio pull request #5
Opened 2022-01-18 15:41 UTC by moise-mulungu

From this branch I added the following contents:
-A section called footer
- Used the form with a value "action" and a method with "post"
- Applied hover and active CSS properties.
- Updated my "contact me" page

2022-01-18 16:34 UTC, medaminedev66 requested changes
Hi @moise-mulungu , :wave:

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️

_See the inline comments below for more required changes_

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-18 16:34 UTC, medaminedev66 commented on index.html
> +            <textarea class="box" placeholder="Enter text here"></textarea>
- [ ] Following the project requirements, All input fields should have the required attribute to activate the validation on submit. Kindly add it 😃.
- [ ] Message input also should have `maxlength="500"` attribute.

2022-01-18 16:34 UTC, medaminedev66 commented on index.html
>              <input type="text" class="input" placeholder="Email address">
- [ ] Following the project requirements, the email input's `type` should equal `email`

2022-01-18 16:34 UTC, medaminedev66 commented on index.html
>              <hr>
- [ ] Please make sure that the form uses the `action` and `method` attribute to integrate with [formspree service](https://formspree.io/html).
* `action` value should be similar to `https://formspree.io/f/{form_id}`
* `method` value equals `POST`
- [ ] You should also consider that the name input should have `maxlength="30"` attribute.

2022-01-18 21:24 UTC, medaminedev66 requested changes
Hi @moise-mulungu, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️

_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-18 21:24 UTC, medaminedev66 commented on index.html
> +            <button type="button" class="touch">Get in touch</button>
- [ ] You have done a great job by implementing the requested changes. But we still cannot submit the form. Kindly change the type of the button from `button` to `submit`.
- [ ] Please before request another review, make sure your form is submitted successfully. You should see this message below after submitting the form:
<img width="275" alt="image" src="https://user-images.githubusercontent.com/77190203/150020550-08a6d654-7eea-49d3-a31e-c44e950d8fda.png">

2022-01-19 10:13 UTC, moise10r approved these changes
<h1>Status: Approve  :champagne:  :+1: :confetti_ball: 

### **Hi @moise-mulungu** , 

### **Congratulations! 🎉 Project Approved ✅**

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 


### To Highlight :1st_place_medal: 

- The form is submitted successfully with valid input values :rocket: 


Cheers and Happy coding!👏👏👏💻  

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-19 10:16 UTC, merged